### ISSUE TITLE
Is it possible to increase the connection timeout to the SQL server?

### ISSUE THREAD

**Issue by IZaiarnyi** [JesseChavez/activerecord-jdbc-adapter#9]
First of all, thank you for this adapter as an activity in the activerecord-sqlserver-adapter thread seems has stopped.

I had started to migrate from tiny_tds to activerecord-jdbc-alt-adapter and faced with a timeout issue. 
It occurs from time to time when a connection is slow and takes more than ˜15 seconds

ActiveRecord::JDBCError: The TCP/IP connection to the host host.test.net, port 1433 has failed. Error: "connect timed out. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
arjdbc/jdbc/RubyJdbcConnection.java:552:in `initialize'

Are you aware of how to explicitly set the connection timeout for the SQL server?

**Comment by JesseChavez** [comment]
Hi there,

Sorry for the late rely, I've got very busy lately.

I recommend you check your network setup, even 15 second is not acceptable for a database connection time out.

But if you really want to change the `login_timeout` setting or any other setting by using the `url` setting, something like:

```yml
# SQL Server (2012 or higher required)
#

default: &default
  adapter: sqlserver
  encoding: utf8

development:
  <<: *default
  url: 'jdbc:sqlserver://localhost:1433;databaseName=sam_development;loginTimeout=20'
  username: dev
  password: password

test:
  <<: *default
  url: 'jdbc:sqlserver://localhost:1433;databaseName=sam_test;loginTimeout=20'
  username: test
  password: password

production:
  <<: *default
  username:
  password:
```
Additionally, in the latest release I added the `login_timeout` setting as stand alone setting, do
someting like this:

```yml
# SQL Server (2012 or higher required)
#

default: &default
  adapter: sqlserver
  encoding: utf8

development:
  <<: *default
  host: localhost
  database: sam_development
  username: dev
  password: password
  login_timeout: 22

test:
  <<: *default
  host: localhost
  database: sam_test
  username: test
  password: password
  login_timeout: 22

production:
  <<: *default
  host: localhost
  database: sam52_production
  username:
  password:
```
You have to use the latest version of the  `activerecord-jdbc-alt-adapter` gem though (version 52.4.0).
